/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_universAAL_messageClassifcationLayer_MCL_MessageDelivery */

#ifndef _Included_org_universAAL_messageClassifcationLayer_MCL_MessageDelivery
#define _Included_org_universAAL_messageClassifcationLayer_MCL_MessageDelivery
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_universAAL_messageClassifcationLayer_MCL_MessageDelivery
 * Method:    timer_trigger
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_universAAL_messageClassifcationLayer_MCL_MessageDelivery_timer_1trigger
  (JNIEnv *, jobject);

/*
 * Class:     org_universAAL_messageClassifcationLayer_MCL_MessageDelivery
 * Method:    eventHandler
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_org_universAAL_messageClassifcationLayer_MCL_MessageDelivery_eventHandler
  (JNIEnv *, jobject, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
